### ISSUE TITLE
Parse error with some WSQ files

### ISSUE THREAD

**Issue by mbert** [kareez/jnbis#15]
I have some WSQs created from paper scans which cause a parse error:

java.lang.RuntimeException: ERROR : getc_marker_wsq : No SOB, Table, or comment markers : 65441
        at org.jnbis.internal.WsqDecoder.getCMarkerWSQ(WsqDecoder.java:107) ~[jnbis-2.0.0.jar!/:na]
        at org.jnbis.internal.WsqDecoder.huffmanDecodeDataMem(WsqDecoder.java:730) ~[jnbis-2.0.0.jar!/:na]
        at org.jnbis.internal.WsqDecoder.decode(WsqDecoder.java:39) ~[jnbis-2.0.0.jar!/:na]

It looks like the end-of-input marker WsqHelper.EOI_WSQ is unexpected here. 

Not sure if this is a correct solution, but the attached patch helped in my particular case.

[wsqdecoder.zip](https://github.com/kareez/jnbis/files/1205242/wsqdecoder.zip)

**Comment by tpaulinoa** [comment]
We had the same problem with some NIST files and this patch worked fine.
Thank you @mbert

**Comment by kareez** [comment]
@mbert @tpaulinoa Thank you for the patch.  please feel free to submit PR for any new feature or bug fix.
